//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class MyApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    getAllLearningExperiences(body: LearningExperienceListQueryDTO | undefined): Promise<LearningExperienceDTO[]> {
        let url_ = this.baseUrl + "/api/LearningExperience/GetAllLearningExperiences";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllLearningExperiences(_response);
        });
    }

    protected processGetAllLearningExperiences(response: Response): Promise<LearningExperienceDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(LearningExperienceDTO.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result400 = resultData400 !== undefined ? resultData400 : <any>null;
    
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LearningExperienceDTO[]>(null as any);
    }

    /**
     * @return OK
     */
    getWeatherForecast(): Promise<WeatherForecast[]> {
        let url_ = this.baseUrl + "/WeatherForecast";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetWeatherForecast(_response);
        });
    }

    protected processGetWeatherForecast(response: Response): Promise<WeatherForecast[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(WeatherForecast.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WeatherForecast[]>(null as any);
    }
}

export class AddressDTO implements IAddressDTO {
    street?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    zipCode?: string | undefined;
    country?: string | undefined;

    constructor(data?: IAddressDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.street = _data["Street"];
            this.city = _data["City"];
            this.state = _data["State"];
            this.zipCode = _data["ZipCode"];
            this.country = _data["Country"];
        }
    }

    static fromJS(data: any): AddressDTO {
        data = typeof data === 'object' ? data : {};
        let result = new AddressDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Street"] = this.street;
        data["City"] = this.city;
        data["State"] = this.state;
        data["ZipCode"] = this.zipCode;
        data["Country"] = this.country;
        return data;
    }
}

export interface IAddressDTO {
    street?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    zipCode?: string | undefined;
    country?: string | undefined;
}

export class LearningExperienceDTO implements ILearningExperienceDTO {
    id?: number;
    from?: Date;
    to?: Date | undefined;
    isRemote?: boolean;
    title?: string | undefined;
    company?: string | undefined;
    address?: AddressDTO;
    description?: string | undefined;

    constructor(data?: ILearningExperienceDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.from = _data["From"] ? new Date(_data["From"].toString()) : <any>undefined;
            this.to = _data["To"] ? new Date(_data["To"].toString()) : <any>undefined;
            this.isRemote = _data["IsRemote"];
            this.title = _data["Title"];
            this.company = _data["Company"];
            this.address = _data["Address"] ? AddressDTO.fromJS(_data["Address"]) : <any>undefined;
            this.description = _data["Description"];
        }
    }

    static fromJS(data: any): LearningExperienceDTO {
        data = typeof data === 'object' ? data : {};
        let result = new LearningExperienceDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["From"] = this.from ? this.from.toISOString() : <any>undefined;
        data["To"] = this.to ? this.to.toISOString() : <any>undefined;
        data["IsRemote"] = this.isRemote;
        data["Title"] = this.title;
        data["Company"] = this.company;
        data["Address"] = this.address ? this.address.toJSON() : <any>undefined;
        data["Description"] = this.description;
        return data;
    }
}

export interface ILearningExperienceDTO {
    id?: number;
    from?: Date;
    to?: Date | undefined;
    isRemote?: boolean;
    title?: string | undefined;
    company?: string | undefined;
    address?: AddressDTO;
    description?: string | undefined;
}

export class LearningExperienceListQueryDTO implements ILearningExperienceListQueryDTO {
    sortDirection?: SortDirection;
    sortExpression?: string | undefined;
    pageIndex?: number | undefined;
    pageSize?: number | undefined;
    description?: string | undefined;

    constructor(data?: ILearningExperienceListQueryDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.sortDirection = _data["SortDirection"];
            this.sortExpression = _data["SortExpression"];
            this.pageIndex = _data["PageIndex"];
            this.pageSize = _data["PageSize"];
            this.description = _data["Description"];
        }
    }

    static fromJS(data: any): LearningExperienceListQueryDTO {
        data = typeof data === 'object' ? data : {};
        let result = new LearningExperienceListQueryDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["SortDirection"] = this.sortDirection;
        data["SortExpression"] = this.sortExpression;
        data["PageIndex"] = this.pageIndex;
        data["PageSize"] = this.pageSize;
        data["Description"] = this.description;
        return data;
    }
}

export interface ILearningExperienceListQueryDTO {
    sortDirection?: SortDirection;
    sortExpression?: string | undefined;
    pageIndex?: number | undefined;
    pageSize?: number | undefined;
    description?: string | undefined;
}

export enum SortDirection {
    _0 = 0,
    _1 = 1,
}

export class WeatherForecast implements IWeatherForecast {
    date?: Date;
    temperatureC?: number;
    readonly temperatureF?: number;
    summary?: string | undefined;

    constructor(data?: IWeatherForecast) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["Date"] ? new Date(_data["Date"].toString()) : <any>undefined;
            this.temperatureC = _data["TemperatureC"];
            (<any>this).temperatureF = _data["TemperatureF"];
            this.summary = _data["Summary"];
        }
    }

    static fromJS(data: any): WeatherForecast {
        data = typeof data === 'object' ? data : {};
        let result = new WeatherForecast();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Date"] = this.date ? formatDate(this.date) : <any>undefined;
        data["TemperatureC"] = this.temperatureC;
        data["TemperatureF"] = this.temperatureF;
        data["Summary"] = this.summary;
        return data;
    }
}

export interface IWeatherForecast {
    date?: Date;
    temperatureC?: number;
    temperatureF?: number;
    summary?: string | undefined;
}

function formatDate(d: Date) {
    return d.getFullYear() + '-' + 
        (d.getMonth() < 9 ? ('0' + (d.getMonth()+1)) : (d.getMonth()+1)) + '-' +
        (d.getDate() < 10 ? ('0' + d.getDate()) : d.getDate());
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super(message);
        this.name = 'ApiException';
        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}